### ISSUE TITLE
Provide Xamarin samples with a custom login

### ISSUE THREAD

**Issue by mraible** [okta/okta-oidc-xamarin#15]
Most of our SDKs have samples. For our mobile SDKs, we're trying to improve developer docs to explicitly state that it's unlikely you can embed the Sign-In Widget and you're better off building a custom UI. Here's a snippet of the docs I'm writing:

```
The good news is our mobile SDKs provide support for you to build your own UI.

- Android:
    - [Sign in with your own UI](https://github.com/okta/okta-oidc-android#Sign-in-with-your-own-UI)
    - [Custom Sign In Example](https://github.com/okta/samples-android/tree/master/custom-sign-in)
- iOS:
    - [Authenticate a User](https://github.com/okta/okta-auth-swift#authenticate-a-user)
    - [Okta iOS Custom Sign In Example](https://github.com/okta/samples-ios/tree/master/custom-sign-in)
- React Native
    - todo: https://github.com/okta/okta-react-native has no docs like Android does
    - [Okta React Native Custom Sign In Example](https://github.com/okta/samples-js-react-native/tree/master/custom-sign-in)
- Xamarin
	- todo: link to code section of Xamarin SDK README that shows code for custom UI
    - todo: link to custom sign in example
```

I need help with the last two items for Xamarin. Thanks!
